### ISSUE TITLE
Doesn't work in vagrant box

### ISSUE THREAD

**Issue by labbydev** [palantirnet/butler#4]
Seems to be a performance issue with the way that Virtual Box handles the NFS Mount, should be tested with VMWare to see if that would solve the problem or not.

**Comment by gleroux02** [comment]
I have the drupal skeleton built and am in the process of installing the dependencies (taking forever) It is really quite the pain to get everything setup for it to run, and I'd prefer to figure it out once and add it back into our skeleton box.

**Comment by labyrwa** [comment]
@gleroux02 Butler dependencies or skeleton dependencies?

**Comment by gleroux02** [comment]
Butler ones

**Comment by labyrwa** [comment]
I'm playing with Butler on LawRevu (since that's a site that I can get up and running), so I'm going to record some notes in this Issue as well. Feel free to ignore them.

My steps:
* Git clone Butler in the project root
* SSH into vagrant
* cd `butler`
* run `fed-init.sh`
* runs fine (doesn't download the module)
  * the module won't download because you're not in the drupal root
  * according to the LawRevu README the command we should be using to add modules is `composer require drupal/css_link` however I believe that that would still have to be run from the project root and not the butler root which is where `fed-init.sh` needs to be run. **UNLESS** we start git cloning Butler and then running `butler/fed-init.sh` also from the project root <-- things to try.
  * It did not add any of the npm dependencies when I tried running `fed-init.sh` inside the box.
* Since it didn't install the dependencies inside the box, I went back to my host machine and ran `fed-init.sh` again to install the dependencies, which appears to have worked
* Navigate back to the vagrant box and run `gulp` to see if it works
  * Throws a sculpin error

**Comment by labyrwa** [comment]
On the LawRevu VM I have switched over to the **jekyll** version. 

My steps
* ran `sudo npm install browser-sync compass-options gulp gulp-autoprefixer gulp-changed gulp-compass gulp-cssmin gulp-imagemin gulp-inject gulp-jscs gulp-jscs-stylish gulp-jshint gulp-rename gulp-scss-lint gulp-sitespeedio gulp-uglify jshint-checkstyle-file-reporter --save-dev` on my host machine
* took forever but it seems to have installed everything appropriately
* Navigate back to vagrant machine
* run `gulp`
* received the following error

``` 
/var/www/sites/lawrevu.local/butler/node_modules/gulp/node_modules/orchestrator/index.js:51
                                throw new Error('Task '+name+' dependency '+item+' is not a string');
                                      ^
Error: Task browser-sync-prototype-only dependency undefined is not a string
    at /var/www/sites/lawrevu.local/butler/node_modules/gulp/node_modules/orchestrator/index.js:51:11
    at Array.forEach (native)
    at Gulp.Orchestrator.add (/var/www/sites/lawrevu.local/butler/node_modules/gulp/node_modules/orchestrator/index.js:49:7)
    at Object.<anonymous> (/var/www/sites/lawrevu.local/butler/Gulpfile.js:146:6)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:185:9)
    at /usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:159:9
    at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:99:14
```

**Comment by gleroux02** [comment]
I've added an issue to the drupal skeleton repo to add the libyaml library. I've consistently run into an error where that library needs to be installed before I can proceed with installing butler within vagrant. https://github.com/palantirnet/drupal-skeleton/issues/31
