### ISSUE TITLE
THE SOCKETS ARE OVERLOADED!

### ISSUE THREAD

**Issue by aCyborg** [palantirnet/butler#57]
'events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: stdout maxBuffer exceeded.
    at Socket.<anonymous> (child_process.js:792:12)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at Pipe.onread (net.js:538:20)'

[npm-debug.txt](https://github.com/palantirnet/butler/files/477558/npm-debug.txt)

**Comment by zendoodles** [comment]
@aCyborg It might help if you describe what you did to get this. 

"stdout maxBuffer exceeded" means the output from your command is too much. 

We got this on UWEC at first when we implemented the a11y testing because there was so much. If it's linting, it could help to only run the linter on some things to reduce the output. Also, look at PR #52 which ignores the double-single quotes things because we seem to ignore those warnings anyway, so why clutter up the already verbose output with them.

Alternatively, you can pipe the output into a file instead of stdout and the problem should go away.

**Comment by aCyborg** [comment]
I don't remember what this was about, and haven't run into the problem since, so I'm going to close this.
